Repository SU-SWS/chem_h_subtheme, pull requests merged in 2023-09, with the labels that each got.

#69 CHEMH-245: Halfpill title banner
  chem_h_subtheme.react_behaviors.yml
  dist/css/chem_h_subtheme.css
  src/js/chem_h_subtheme.behaviors.js
  src/scss/components/banner/_banner-general.scss
  src/scss/components/banner/_halfpill-title.scss
  src/scss/components/banner/_halfpill.scss
  src/scss/components/banner/_homepage.scss
  src/scss/components/banner/index.scss
Labels: size/s

#68 CHEMH-77: A fullpill banner
  chem_h_subtheme.react_behaviors.yml
  chem_h_subtheme.theme
  dist/assets/png/fullpill-bg.png
  dist/assets/svg/fullpill-bg.svg
  dist/css/chem_h_subtheme.css
  src/assets/png/fullpill-bg.png
  src/assets/svg/fullpill-bg.svg
  src/scss/components/banner/_banner--fullpill.scss
  src/scss/components/banner/_banner--general.scss
  src/scss/components/banner/_banner--halfpill-title.scss
  src/scss/components/banner/_banner--halfpill.scss
  src/scss/components/banner/_banner--homepage.scss
  src/scss/components/banner/index.scss
  src/scss/components/card/index.scss
  src/scss/utilities/variables/_sizes.scss
  src/scss/utilities/variables/index.scss
Labels: size/s

#55 CHEMH-89 | @jdwjdwjdw | Style event node and teaser
  dist/css/chem_h_subtheme.css
  src/js/chem_h_subtheme.behaviors.js
  src/scss/components/events/_event-card.scss
  src/scss/components/events/_event-node.scss
  src/scss/components/events/index.scss
  src/scss/components/index.scss
  src/scss/theme/_button.scss
  src/scss/theme/_headings.scss
  templates/components/event-card/pattern-events-card.html.twig
Labels: size/m

#67 CHEMH-83 | @jdwjdwjdw | Structure and style News node page
  dist/css/chem_h_subtheme.css
  src/js/chem_h_subtheme.behaviors.js
  src/scss/components/events/_event-node.scss
  src/scss/components/news/_news-node.scss
  src/scss/theme/_button.scss
  templates/components/news/node--stanford-news.html.twig
Labels: size/s

#71 ChemH-246 | @jdwjdwjdw | Add button grid
  dist/css/chem_h_subtheme.css
  src/scss/theme/_button.scss
Labels: size/xs

#72 CHEMH-000: fix to a background color bug
  dist/css/chem_h_subtheme.css
  src/js/chem_h_subtheme.behaviors.js
  src/scss/components/banner/_banner--halfpill-title.scss
Labels: size/xs
