Repository SU-SWS/chem_h_subtheme, pull requests merged in 2024-02, with the labels that each got.

#84 CHEMH-263: changing max width to 2000px
  dist/css/chem_h_subtheme.css
  src/scss/components/banner/_banner--halfpill-title.scss
  src/scss/components/banner/_banner--halfpill.scss
Labels: size/s

#85 Fixing the decanter references and updated webpack and node
  .nvmrc
  README.md
  chem_h_subtheme.info.yml
  dist/assets/fullpill-bg.svg
  dist/assets/header-000-mobile--cropped.png
  dist/assets/header-sm-000--cropped.png
  dist/assets/png/Sarafan_ChEM-H_Gradient_dark_16.9.png
  dist/assets/png/Sarafan_ChemH_Logo.png
  dist/assets/png/fullpill-bg.png
  dist/assets/png/header-big-000-tall--cropped.png
  dist/assets/png/header-big-000-tall.png
  dist/assets/svg/icon_arrow_closed_hover_red.svg
  dist/assets/svg/icon_arrow_closed_red.svg
  dist/assets/svg/icon_arrow_down_red.svg
  dist/assets/svg/icon_arrow_down_stone.svg
  dist/assets/svg/icon_arrow_open_red.svg
  dist/assets/svg/icon_close_red.svg
  dist/assets/svg/icon_drop_down_red.svg
  dist/assets/svg/icon_east_black.svg
  dist/assets/svg/icon_east_black_big.svg
  dist/assets/svg/icon_east_white.svg
  dist/assets/svg/icon_east_white_big.svg
  dist/assets/svg/icon_expand_more_red.svg
  dist/assets/svg/icon_expand_more_white.svg
  dist/assets/svg/icon_primary_nav_caret.svg
  dist/assets/svg/icon_primary_nav_caret_red.svg
  dist/assets/svg/icon_search_black.svg
  dist/assets/svg/icon_search_red.svg
  dist/assets/svg/icon_secondary_nav_caret.svg
  dist/css/chem_h_subtheme.css
  package-lock.json
  package.json
  templates/block--stanford-basic-search.html.twig
  templates/components/news/node--stanford-news.html.twig
  webpack.config.js
  yarn.lock
Labels: size/xl

#87 [CHEMH-264] | @jdwjdwjdw | Update webpack
  README.md
  chem_h_subtheme.info.yml
  chem_h_subtheme.libraries.yml
  package.json
  src/js/chemhsubtheme.behaviors.js
  src/js/scripts.js
  webpack.config.js
  yarn.lock
Labels: size/xs

#88 CHEMH-000 | @jdwjdwjdw | Update event node styles
  README.md
  chem_h_subtheme.info.yml
  dist/css/chem_h_subtheme.css
  src/scss/components/events/_event-node.scss
Labels: size/xs
